### ISSUE TITLE
Navigation and pagination modules are not working

### ISSUE THREAD

**Issue by daffamumtaz2361** [Orest-2/swiper-vue2#2]
I'm not sure if other modules works, but I tried using navigation and pagination modules, and both are not working. Navigation buttons appear but does nothing when clicked. While pagination isn't showing at all. [Codesandbox example](https://codesandbox.io/s/swiper-vue2-pagination-wfmnn)

**Comment by gopherest** [comment]
fixed
after package update code should look like
```vue
import { Navigation, Pagination } from "swiper";
import { SwiperCore, Swiper, SwiperSlide } from "swiper-vue2";

// Import Swiper styles
import "swiper/swiper-bundle.css";

SwiperCore.use([Navigation, Pagination]);
...
```

**Comment by daffamumtaz2361** [comment]
The usage section in readme still says "`swiper-vue2` exports 2 components" when it should be 3
