### ISSUE TITLE
console.log in distribution files

### ISSUE THREAD

**Issue by sdussaut** [Orest-2/swiper-vue2#3]
Hello!

Thanks for the package!
I have one request: there seems to be debug information output in the files when exported for distribution. Is it possible to get rid of it? Thanks!

![Capture d’écran 2022-02-11 à 09 58 58](https://user-images.githubusercontent.com/643853/153564523-580a7bf4-cbfe-47cd-bd44-7d5aaa660f9c.png)

**Comment by gopherest** [comment]
Hello, fixed

**Comment by sdussaut** [comment]
Thank you very much, that was very fast :-)
