### ISSUE TITLE
SwiperCore cannot be imported

### ISSUE THREAD

**Issue by Reda-H** [Orest-2/swiper-vue2#4]
As the tile says, SwiperCore cannot be imported, there's only two elements that are exported from the package.

**Comment by gopherest** [comment]
Hello, what package version are you using?

**Comment by gopherest** [comment]
SwiperCore is available starts from version 1.0.5

**Comment by Reda-H** [comment]
I'm using swiper-vue2 version 1.0.6 at the moment, and I get the following error:
```
Module '"swiper-vue2"' has no exported member 'SwiperCore'.
```

**Comment by gopherest** [comment]
can you please send the part of the code of import SwiperCore

**Comment by hamonCordova** [comment]
Same here. Please, can you fix it?
You can se on "swiper-vue2.d.ts" that the SwiperCore isn't exported. Same for 1.0.5 and 1.0.6

**Comment by gopherest** [comment]
fixed
