### ISSUE TITLE
can i use a key that is not n?

### ISSUE THREAD

**Issue by FrancescoCiannavei** [Orest-2/swiper-vue2#7]
hey, i am having problems with swiper, i am trying to create a slider with elements returned from the "the movie db API" doing:
swiper-slide v-for="film in movies" :key="film.id" . When it creates the slider the elements don't loop even if i defined :loop='true' and when all the elements have been shown i can slide infinitely with an empty slid

an example:
https://user-images.githubusercontent.com/64163256/168277518-314d4e63-0721-413d-a165-f5baf991dbda.mp4

the section of the code where swiper is included
[code.txt](https://github.com/Orest-2/swiper-vue2/files/8686787/code.txt)

**Comment by gopherest** [comment]
hi
added one more example for your case [movie example](https://github.com/Orest-2/swiper-vue2/blob/master/example/src/App.vue#L76)
can you please try to run it locally
because it works for me

**Comment by FrancescoCiannavei** [comment]
i  think the problem is that i am getting the images from an api and i am reciving the images when i give an input, before that the array is empty, i tried to give to a container v-if='name of the array' to make it perform that section of the code when i got the array but it still is not working

**Comment by FrancescoCiannavei** [comment]
if you want to take a look at my project the repo is here
https://github.com/Franky5831/vue-boolflix

**Comment by gopherest** [comment]
changed your code to make swiper work with a dynamic list [main.txt](https://github.com/Orest-2/swiper-vue2/files/8695030/main.txt)

**Comment by FrancescoCiannavei** [comment]
https://user-images.githubusercontent.com/64163256/168478788-bcd65285-5015-4bc8-b44d-26676ee397ef.mp4

it kinda works, the problem is that the last 2 cards are not being shown

**Comment by FrancescoCiannavei** [comment]
i gave it loop true so you can't really notice that you are skipping 2 cards XD

**Comment by gopherest** [comment]
the problem with styles

![Screenshot_1](https://user-images.githubusercontent.com/20842843/168483558-b78b833e-a8e7-4797-8e44-dc995837346d.png)

updated styles which fix this issue [main.txt](https://github.com/Orest-2/swiper-vue2/files/8695406/main.txt)

styles should be applied to slider content instead swiper slide directly as it changes its styles based on content and overwrites user styles

**Comment by FrancescoCiannavei** [comment]
yeah, i applyied that a while ago and forgot about it, now it's perfect, thanks
